# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'com.test.satracking.sdk.demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for com.test.satracking.sdk.demo
  pod 'SATrackingSDK' , '~> 1.1.1'
end

# fix that error https://github.com/CocoaPods/CocoaPods/issues/10185#issuecomment-722332929
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
end
end
end